const mongoose = require("mongoose");
const jwt = require("jsonwebtoken");
const Joi = require("joi");
const validatePw = require("joi-password-complexity");
const { generateUsername } = require("unique-username-generator");

const autoGeneratedusername = generateUsername("-");


const userSchema = new mongoose.Schema({
		firstName: { type: String },
		lastName: { type: String },
		email: { type: String, required: true },
		contactNo: { type: String },
		role: { type: String, default: "CLIENT" },
		password: { type: String, required: true },
		username: { type: String, default: autoGeneratedusername },
		pic: { type: String, default: "https://icon-library.com/images/anonymous-avatar-icon/anonymous-avatar-icon-25.jpg" },
		address1: { type: String },
		address2: { type: String },
		city: { type: String },
		state: { type: String },
	},
	{ timestamps: true }
);

userSchema.methods.generateAuthToken = function () {
	const token = jwt.sign({ _id: this._id }, process.env.JWT_PRIVATEKEY, {
		expiresIn: "7d",
	});
	return token;
};

const User = mongoose.model("user", userSchema);

const validate = (data) => {
	const schema = Joi.object({
		firstName: Joi.string().label("First Name"),
		lastName: Joi.string().label("Last Name"),
		email: Joi.string().email().required().label("Email"),
        contactNo: Joi.string().label("Contact No"),
		role: Joi.string().label("User Role"),
		password: validatePw().required().label("Password"),
		username: Joi.string().label("Username"),
		pic: Joi.string().label("Profile Pic"),
		address1: Joi.string().label("Address1"),
		address2: Joi.string().label("Address2"),
		city: Joi.string().label("City"),
		state: Joi.string().label("State"),
	});
	return schema.validate(data);
};

module.exports = { User, validate };